// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaCart.Services.Catalog.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovaCart.Services.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NovaCart.Services.Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Electronic devices and gadgets",
                            Name = "Electronics",
                            Slug = "electronics"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Apparel and fashion items",
                            Name = "Clothing",
                            Slug = "clothing"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Books and publications",
                            Name = "Books",
                            Slug = "books"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Home and garden products",
                            Name = "Home & Garden",
                            Slug = "home-garden"
                        });
                });

            modelBuilder.Entity("NovaCart.Services.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000001"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Premium noise-cancelling wireless headphones with 30-hour battery life.",
                            Name = "Wireless Bluetooth Headphones",
                            Slug = "wireless-bluetooth-headphones",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000002"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Adjustable aluminum smartphone stand for desk use.",
                            Name = "Smartphone Stand",
                            Slug = "smartphone-stand",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000003"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader.",
                            Name = "USB-C Hub Adapter",
                            Slug = "usb-c-hub-adapter",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000004"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "RGB mechanical keyboard with Cherry MX switches.",
                            Name = "Mechanical Keyboard",
                            Slug = "mechanical-keyboard",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000005"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "100% organic cotton crew-neck t-shirt.",
                            Name = "Cotton T-Shirt",
                            Slug = "cotton-t-shirt",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000006"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Classic straight-fit denim jeans.",
                            Name = "Denim Jeans",
                            Slug = "denim-jeans",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000007"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Lightweight running sneakers with cushioned sole.",
                            Name = "Running Sneakers",
                            Slug = "running-sneakers",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000008"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A Handbook of Agile Software Craftsmanship by Robert C. Martin.",
                            Name = "Clean Code",
                            Slug = "clean-code",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000009"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tackling Complexity in the Heart of Software by Eric Evans.",
                            Name = "Domain-Driven Design",
                            Slug = "domain-driven-design",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000010"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Your Journey To Mastery by David Thomas and Andrew Hunt.",
                            Name = "The Pragmatic Programmer",
                            Slug = "the-pragmatic-programmer",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000011"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Handcrafted ceramic plant pot with drainage hole.",
                            Name = "Ceramic Plant Pot",
                            Slug = "ceramic-plant-pot",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000012"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Dimmable LED desk lamp with touch control.",
                            Name = "LED Desk Lamp",
                            Slug = "led-desk-lamp",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0001-0001-000000000013"),
                            CategoryId = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "5-piece stainless steel garden tool set.",
                            Name = "Garden Tool Set",
                            Slug = "garden-tool-set",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("NovaCart.Services.Catalog.Domain.Entities.Category", b =>
                {
                    b.HasOne("NovaCart.Services.Catalog.Domain.Entities.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("NovaCart.Services.Catalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("NovaCart.Services.Catalog.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("NovaCart.Services.Catalog.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasData(
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000001"),
                                    Amount = 79.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000002"),
                                    Amount = 24.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000003"),
                                    Amount = 39.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000004"),
                                    Amount = 129.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000005"),
                                    Amount = 19.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000006"),
                                    Amount = 49.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000007"),
                                    Amount = 89.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000008"),
                                    Amount = 34.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000009"),
                                    Amount = 44.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000010"),
                                    Amount = 39.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000011"),
                                    Amount = 22.50m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000012"),
                                    Amount = 34.99m,
                                    Currency = "USD"
                                },
                                new
                                {
                                    ProductId = new Guid("a1b2c3d4-0002-0001-0001-000000000013"),
                                    Amount = 45.00m,
                                    Currency = "USD"
                                });
                        });

                    b.Navigation("Category");

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("NovaCart.Services.Catalog.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
